trigger:
- jitu

variables:
  Environment: 'dev'   # change this in pipeline UI or YAML (prod/dev)

pool:
  name: robo

steps:

# ðŸ”¹ Step 1: Terraform Init
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendServiceArm: 'Framework'
    backendAzureRmResourceGroupName: 'todoapprg1'
    backendAzureRmStorageAccountName: 'stgtodoaap123'
    backendAzureRmContainerName: 'jitu'
    backendAzureRmKey: 'terraform.tfstate'

# ðŸ”¹ Step 2: Terraform Plan
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    environmentServiceNameAzureRM: 'Framework'

# ðŸ”¹ Step 3: Terraform Apply (Conditional)
- task: TerraformTask@5
  displayName: 'Terraform Apply (only for prod)'
  condition: and(succeeded(), eq(variables['Environment'], 'dev'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    environmentServiceNameAzureRM: 'Framework'




