trigger:
- main

pool: robo


steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'framework-service connection'
    ScriptType: 'InlineScript'
    Inline: |
      cd az login
      terraform init
    azurePowerShellVersion: 'LatestVersion'
